language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local_dir: build
