version: 0.2

env:
  variables:
    NODE_ENV: "development"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:

  pre_build:
    commands:
      - yarn

  build:
    commands:
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - './node_modules/**/*'